name: Publish to PyPI
on:
  workflow_dispatch:
  release:
    types:
      - published
#  push:
#    tags:
#      - "[0-9]+.[0-9]+*"

jobs:
  publish:
    name: Build and publish
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install --upgrade setuptools wheel twine
      - run: python setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          skip_existing: true
